packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  unocss: 66.1.0-beta.5
catalogs:
  cli:
    '@antfu/eslint-config': ^6.0.0
    '@antfu/ni': ^26.2.0
    bumpp: ^10.3.1
    esbuild: ^0.25.11
    eslint: ^9.37.0
    lint-staged: ^16.2.4
    simple-git-hooks: ^2.13.1
    tsx: ^4.20.6
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.1.10
  frontend:
    nanoevents: ^9.1.0
  inlined:
    '@antfu/utils': ^9.3.0
  playground:
    '@vitejs/plugin-vue': ^6.0.1
    '@vueuse/core': ^13.9.0
    vue: ^3.5.22
    vue-tsc: ^3.1.1
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.8.0
  utils:
    tinyexec: ^1.0.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
