packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  unocss: 66.1.0-beta.5
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.3.0
    bumpp: ^10.1.0
    esbuild: ^0.25.1
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.12.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.2
  frontend:
    nanoevents: ^9.1.0
  inlined:
    '@antfu/utils': ^9.1.0
  playground:
    '@vitejs/plugin-vue': ^5.2.3
    '@vueuse/core': ^13.0.0
    vue: ^3.5.13
    vue-tsc: ^2.2.8
  testing:
    vitest: ^3.0.9
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
